# SearXNG configuration for NEXORA SEARCH on Render
use_default_settings: true

general:
  debug: false
  instance_name: "NEXORA Search Engine"
  donation_url: false
  contact_url: false

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "10c6c83a7480bb964acc5985040a4b28b1e2f7f941bbd9c4e3ca6c67f35b71d7"
  limiter: false
  image_proxy: true
  method: "GET"

search:
  safe_search: 0
  autocomplete: "google"
  formats:
    - html
    - json

outgoing:
  request_timeout: 6.0
  max_request_timeout: 10.0

engines:
  - name: brave
    disabled: true

  - name: pinterest
    disabled: true

  - name: ahmia
    disabled: true

  - name: torch
    disabled: true
